apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-api
  namespace: tp2
  labels:
    app: logic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logic-api
  template:
    metadata:
      labels:
        app: logic-api
    spec:
      volumes:
        - name: nltk-data
          emptyDir: {}
      initContainers:
        - name: download-nltk-corpora
          image: docker.io/lamine2002/logic-api:submission
          imagePullPolicy: Always
          env:
            - name: NLTK_DATA
              value: /nltk_data
          command: ["sh", "-c"]
          args:
            - >
              python -m textblob.download_corpora -q &&
              python -c "import nltk; nltk.download('punkt_tab', quiet=True)" || true
          volumeMounts:
            - name: nltk-data
              mountPath: /nltk_data
      containers:
        - name: logic-api
          image: docker.io/lamine2002/logic-api:submission
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NLTK_DATA
              value: /nltk_data
          volumeMounts:
            - name: nltk-data
              mountPath: /nltk_data
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: logic-api
  namespace: tp2
spec:
  selector:
    app: logic-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
